# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f015004ce81e874d7901d67a72413dedf50567bed538108fa3d51385bbff6c040272085ba7027b8afe4785ab10e232a6cd2e14a253852415867552f96588398c

test:
  secret_key_base: 8457e34e1cd6515983669e1134076f196e85d1510db04f785ed0212956e88b9f536f61bed816848980975f5e5a569e536fe375b2d4c9251d58f9bcb85b43981a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
